AWSTemplateFormatVersion: '2010-09-09'
Description: >
    Create the repository in Amazon ECR to hold the Docker images of the application
    Capstone project - CI/CD pipeline with Jenkins, Docker and Kubernetes 
    Udacity Could DevOps Nanodgree
    Agoston Pajzs
    CloudFormation template file

Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

    RepoName:
        Description: Repository name to be used in Amazon ECR
        Type: String

    AccountId:
        Description: AWS Account Id
        Type: String

Resources:

    ECRRepository: 
        Type: AWS::ECR::Repository
        Properties: 
            RepositoryName: !Ref RepoName
            RepositoryPolicyText: 
                Version: "2012-10-17"
                Statement: 
                  - Sid: AllowPushPull
                    Effect: Allow
                    Principal: 
                        AWS: 
                        - !Sub "arn:aws:iam::${AccountId}:user/agostonp"
                        - !Sub "arn:aws:iam::${AccountId}:root"
                    Action: 
                        - "ecr:GetDownloadUrlForLayer"
                        - "ecr:BatchGetImage"
                        - "ecr:BatchCheckLayerAvailability"
                        - "ecr:PutImage"
                        - "ecr:InitiateLayerUpload"
                        - "ecr:UploadLayerPart"
                        - "ecr:CompleteLayerUpload"
            Tags: 
              - Key: Name 
                Value: !Sub ${EnvironmentName} ECR Repository

Outputs: 

    ECRRepository:
        Description: A reference to the ECR Repository
        Value: !Ref ECRRepository
        Export:
          Name: !Sub ${EnvironmentName}-ECR-REPO
