AWSTemplateFormatVersion: '2010-09-09'
Description: >
    Create the an EC2 instance as Jenkins Server
    Capstone project - CI/CD pipeline with Jenkins, Docker and Kubernetes 
    Udacity Could DevOps Nanodgree
    Agoston Pajzs
    CloudFormation template file

Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

Resources:

    JenkinsEIP:
        Type: AWS::EC2::EIP
        Properties: 
            Domain: vpc
            Tags: 
              - Key: Name 
                Value: !Sub "${EnvironmentName} Jenkins Server"
      
    JenkinsEIPAssociation:
        Type: AWS::EC2::EIPAssociation
        Properties:
            AllocationId: !GetAtt JenkinsEIP.AllocationId
            InstanceId: !Ref JenkinsEC2Instance

    JenkinsServerSecGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Allow Jenkins and SSH ports to our Jenkins server - SSH from Dummy IP only!
            VpcId:
              Fn::ImportValue: !Sub "${EnvironmentName}-VPCID"
            SecurityGroupIngress:
            - IpProtocol: tcp
              FromPort: 8080
              ToPort: 8080
              CidrIp: 0.0.0.0/0
            - IpProtocol: tcp
              FromPort: 22
              ToPort: 22
              CidrIp: 1.2.3.4/32
            SecurityGroupEgress:
            - IpProtocol: tcp
              FromPort: 0
              ToPort: 65535
              CidrIp: 0.0.0.0/0
            Tags: 
            - Key: Name 
              Value: !Sub "${EnvironmentName} Jenkins Server"

    JenkinsEC2Instance: 
        Type: AWS::EC2::Instance
        Properties: 
            ImageId: ami-03ab4e8f1d88ce614
            KeyName: Ago-Frankfurt-keypair
            SecurityGroupIds:
            - Ref: JenkinsServerSecGroup
            SubnetId:
              Fn::ImportValue: !Sub "${EnvironmentName}-PUB1-SN"
            InstanceType: t2.micro
            BlockDeviceMappings:
            - DeviceName: "/dev/sdk"
              Ebs:
                VolumeSize: '10'
            UserData:
              Fn::Base64: !Sub |
                #!/bin/bash -xe
                exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
                # update all packages
                yum update -y
                # install tidy
                yum install -y tidy
                tidy --version
                # install hadolint
                wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.17.6/hadolint-Linux-x86_64
                chmod +x /bin/hadolint
                hadolint --version
                # install git
                yum install -y git
                git version
                # install docker
                yum install -y docker
                docker --version
                service docker start
                # install kubectl
                curl -o /bin/kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.16.8/2020-04-16/bin/linux/amd64/kubectl
                chmod +x /bin/kubectl
                kubectl version --short --client
                # install java 8
                yum install -y java-1.8.0
                yum remove -y java-1.7.0-openjdk
                java -version
                ##### Download and install Jenkins, for details see: https://d1.awsstatic.com/Projects/P5505030/aws-project_Jenkins-build-server.pdf
                wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
                rpm --import https://pkg.jenkins.io/redhat/jenkins.io.key
                yum install jenkins -y
                yum update –y
                service jenkins start
                # Add users to docker group to allow running docker commands
                usermod -aG docker ec2-user
                usermod -aG docker jenkins
            Tags: 
                - Key: Name 
                  Value: !Sub "${EnvironmentName} Jenkins Server"

Outputs: 

    JenkinsIP: 
        Description: Public (Elastic) IP address of the Jenkins Server
        Value: !Ref JenkinsEIP
        Export:
          Name: !Sub ${EnvironmentName}-JenkinsIP

    JenkinsServerSecGroup:
        Description: The SecurityGroup used to access the Jenkins Server - Change the allowed IP to your own IP!
        Value: !Ref JenkinsServerSecGroup
        Export:
          Name: !Sub ${EnvironmentName}-JenkinsServerSecGroup
