AWSTemplateFormatVersion: '2010-09-09'
Description: >
    Create the an EC2 instance as Jenkins Server
    Capstone project - CI/CD pipeline with Jenkins, Docker and Kubernetes 
    Udacity Could DevOps Nanodgree
    Agoston Pajzs
    CloudFormation template file

Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

Resources:

    JenkinsEIP:
        Type: AWS::EC2::EIP
        Properties: 
            Domain: vpc
    
    JenkinsEIPAssociation:
        Type: AWS::EC2::EIPAssociation
        Properties:
            AllocationId: !GetAtt JenkinsEIP.AllocationId
            InstanceId: !Ref JenkinsEC2Instance

    JenkinsServerSecGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Allow Jenkins and SSH ports to our Jenkins server - SSH from Dummy IP only!
            VpcId:
              Fn::ImportValue: !Sub "${EnvironmentName}-VPCID"
            SecurityGroupIngress:
            - IpProtocol: tcp
              FromPort: 8080
              ToPort: 8080
              CidrIp: 0.0.0.0/0
            - IpProtocol: tcp
              FromPort: 22
              ToPort: 22
              CidrIp: 1.2.3.4/32
            SecurityGroupEgress:
            - IpProtocol: tcp
              FromPort: 0
              ToPort: 65535
              CidrIp: 0.0.0.0/0

    JenkinsEC2Instance: 
        Type: AWS::EC2::Instance
        Properties: 
            ImageId: ami-076431be05aaf8080
            KeyName: Ago-Frankfurt-keypair
            SecurityGroupIds:
            - Ref: JenkinsServerSecGroup
            SubnetId:
              Fn::ImportValue: !Sub "${EnvironmentName}-PUB1-SN"
            InstanceType: t2.micro
            BlockDeviceMappings:
            - DeviceName: "/dev/sdk"
              Ebs:
                VolumeSize: '10'
