AWSTemplateFormatVersion: '2010-09-09'
Description: >
    Create the Kubernetes Cluster and Nodegroup (Amazon EKS)
    Capstone project - CI/CD pipeline with Jenkins, Docker and Kubernetes 
    Udacity Could DevOps Nanodgree
    Agoston Pajzs
    CloudFormation template file

Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

    SshKey:
        Description: SSH key to be used to access servers
        Type: String

    MyIPCIDR: 
        Description: My own local IP address (CIDR notation) to be used to allow SSH to worker nodes
        Type: String

Resources:

    KubeNodegroup:
        Type: 'AWS::EKS::Nodegroup'
        Properties:
            ClusterName:
                Fn::ImportValue: !Sub "${EnvironmentName}-CLUSTER"
            AmiType: AL2_x86_64
            DiskSize: 10
            InstanceTypes:
                - t2.micro
            NodegroupName: "${EnvironmentName}-EKSNodegroup"
            NodeRole: 
                Fn::ImportValue: !Sub "${EnvironmentName}-EKSWorkerNodeRoleArn"
            RemoteAccess:
                Ec2SshKey: !Ref SshKey
                SourceSecurityGroups:
                - !Ref KubeNodesSSHSecGroup
            ScalingConfig:
                MinSize: 2
                DesiredSize: 2
                MaxSize: 2
            Subnets:
                - Fn::ImportValue: !Sub "${EnvironmentName}-PRI1-SN"
                - Fn::ImportValue: !Sub "${EnvironmentName}-PRI2-SN"
            Labels:
                Environment: !Ref EnvironmentName
