AWSTemplateFormatVersion: '2010-09-09'
Description: >
    Create the Kubernetes Cluster and Nodegroup (Amazon EKS)
    Capstone project - CI/CD pipeline with Jenkins, Docker and Kubernetes 
    Udacity Could DevOps Nanodgree
    Agoston Pajzs
    CloudFormation template file

Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

    SshKey:
        Description: SSH key to be used to access servers
        Type: String

    MyIPCIDR: 
        Description: My own local IP address (CIDR notation) to be used to allow SSH to worker nodes
        Type: String

Resources:
    KubeCluster:
        Type: 'AWS::EKS::Cluster'
        Properties:
            Name: !Ref EnvironmentName
            Version: '1.16'
            RoleArn:
                Fn::ImportValue: !Sub "${EnvironmentName}-EKSClusterRoleArn"
            ResourcesVpcConfig:
                SecurityGroupIds:
                - Fn::ImportValue: !Sub "${EnvironmentName}-ControlPlaneSecurityGroup"
                SubnetIds:
                - Fn::ImportValue: !Sub "${EnvironmentName}-PUB1-SN"
                - Fn::ImportValue: !Sub "${EnvironmentName}-PUB2-SN"
                - Fn::ImportValue: !Sub "${EnvironmentName}-PRI1-SN"
                - Fn::ImportValue: !Sub "${EnvironmentName}-PRI2-SN"

    KubeNodesSSHSecGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Allow SSH to Kube (EKS) worker nodes
            VpcId:
                Fn::ImportValue: !Sub "${EnvironmentName}-VPCID"
            SecurityGroupIngress:
            - IpProtocol: tcp
              FromPort: 22
              ToPort: 22
              CidrIp: !Ref MyIPCIDR
            SecurityGroupEgress:
            - IpProtocol: tcp
              FromPort: 0
              ToPort: 65535
              CidrIp: 0.0.0.0/0


Outputs: 

    KubeCluster: 
        Description: A reference to the created EKSCluster
        Value: !Ref KubeCluster
        Export:
          Name: !Sub ${EnvironmentName}-CLUSTER
